### ISSUE TITLE
error message when whitelist file is not listed or found

### ISSUE THREAD

**Issue by Mo-Gul** [pgundlach/lua-check-hyphen#14]
It seems that in the last year (sometime after 2016-06-06) there were some changes that cause the code 

```
\documentclass{standalone}
\usepackage{lua-check-hyphen}
    \LuaCheckHyphen{
        whitelist={%
%            Hyphenation_DE_WhiteList.txt%
        }
    }
\begin{document}
    Nur ein Test.
\end{document}
```

to bring up the error message

> stack traceback:
> 	[C]: in function 'write_nl'
> 	./lua-check-hyphen.lua:223: in function 'enable'
> 	[\directlua]:1: in main chunk.
> \luachekchyphendothings ...achekchyphen.enable() }
>                                                   
> l.28 \begin{document}

now. As far as I have tracked it it rises either when the argument is empty or the listed file doesn't exist.

**Comment by pgundlach** [comment]
This is fixed by 7afcf459ed494bd1bfb65493bef5109d111e03ac
