### ISSUE TITLE
Respect `--output-directory` command line option to TeX engine

### ISSUE THREAD

**Issue by genodeftest** [pgundlach/lua-check-hyphen#17]
Many TeX engines, including `pdflatex`, `xelatex` and `lualatex` support the `--output-directory` command line switch which places all output files to a specific folder. It would be nice to have `lua-check-hyphen` respect this switch too (or `--aux-directory`) so that no auto-generated file "pollutes" the original source folder. This issue is hitting users of TikZ with its externalization library harder as that one will start a separate latex process for every TikZ graphic.

**Comment by pgundlach** [comment]
Good idea. I'll have a look.

**Comment by pgundlach** [comment]
This is uploaded to CTAN and will be distributed soon. Thanks for the suggestion!

**Comment by genodeftest** [comment]
Hm, your commit does not change anything. The `.uhy` files still get placed next to the `.tex` source folders, The package is updated correctly according to TeX's log file: 

    Package: lua-check-hyphen 2018/04/16 v0.7 Hyphenation checking for LuaTeX (PGU)

**Comment by genodeftest** [comment]
Hm, your commit does not change anything. The `.uhy` files still get placed next to the `.tex` files in my source folders, not next to the `.pdf` files in `--output-directory`. The package is updated correctly according to TeX's log file: 

    Package: lua-check-hyphen 2018/04/16 v0.7 Hyphenation checking for LuaTeX (PGU)

**Comment by genodeftest** [comment]
Oh, this fails for me because the code does expect the `--output-directory` switch and its argument to be in 2 separate arguments (i.e. separated by whitespace as in `--output-directory foobar`), which may not be the case as `lualatex` successfully parses `--output-directory=foobar` too.

I have a fix and will upload it later.
