### ISSUE TITLE
Multiple hyphenations per word in whitelist

### ISSUE THREAD

**Issue by Toddy69** [pgundlach/lua-check-hyphen#7]
If a word has multiple breakpoints you have to insert multiple entries in the whitelist. For example:

hy-phenation
hyphen-ation 
hyphena-tion 

If you add an an entry with all possible breaks like hy-phen-a-tion, lua-check-hyphen doesn't recognize correctly hyphenated words. It would be nice to add this feature.

**Comment by pgundlach** [comment]
This is finally fixed in version 0.4.
